server:
  port: 8888
spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunshuo21/file-manager.git
          search-paths: config-repo
          username: 15811543437@163.com
          password: sfcy215211314,.
# Spring boot 2.0的改动较大，/bus/refresh全部整合到actuator里面了，
# 变成了/actuator/bus-refresh,所以之前1.x的management.security.enabled全部失效，不适用于2.0
# 注意：config-server和config-client的配置都需要加上
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8011/eureka/