server:
  port: 8888
spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunshuo21/spring-cloud-demo.git
          search-paths: document/config-repo
          username: 15811543437@163.com
          password: sfcy215211314,.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/
#    serviceUrl:
#      defaultZone: http://localhost:8011/eureka/