server:
  port: 8800
spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunshuo21/spring-cloud-demo.git
          search-paths: document/config-repo
          username: 15811543437@163.com
          password: sfcy215211314,.
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.75.224
    port: 5672
    username: admin
    password: fengzi21
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'