server:
  port: 9001
spring:
  application:
#    name: demo-consumer
    name: node1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
feign:
  hystrix:
    enabled: true
