server:
  port: 8011
spring:
  application:
    name: demo-eureka
eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # 表示是否将自我保护机制开启，默认为true
#  server:
#    enable-self-preservation: false
