
server:
  port: 8801
spring:
  application:
    name: demo-config-client
  cloud:
    config:
      name: neo-config
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: demo-config-server
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/