
server:
  port: 8801
spring:
  application:
    name: demo-config-client
  rabbitmq:
    host: 192.168.75.224
    port: 5672
    username: admin
    password: fengzi21
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh