
server:
  port: 8801
spring:
  application:
    name: demo-config-client
  cloud:
    config:
      name: neo-config
      profile: dev
      uri: http://localhost:8888/
      label: master
# Spring boot 2.0的改动较大，/bus/refresh全部整合到actuator里面了，
# 变成了/actuator/bus-refresh,所以之前1.x的management.security.enabled全部失效，不适用于2.0
# 注意：config-server和config-client的配置都需要加上
management:
  endpoints:
    web:
      exposure:
        include: refresh
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8011/eureka/